### ISSUE TITLE
Stuck in "Waiting for system time to be set..."

### ISSUE THREAD

**Issue by SmokeyLowkey** [mtnbkr88/ESP32CAMVideoRecorder#3]
The code uploaded without issue but when connected to the wifi it loops the "Waiting for system time to be set..." message until the retry count reaches 10. Not sure what the issue is, would appreciate the help. Thank you for your time.

**Comment by mtnbkr88** [comment]
Please verify you have your IP address, the gateway IP address, netmask and DNS IP addresses correct (four fields separated by commas, not periods). This error indicates the ESP32 network cannot reach the time server in the outside world. If you are setting up in an environment that does not have access to the internet, you'll need to comment out the time setting code and find another way to set the time since time is used for all picture and video file names.

**Comment by SmokeyLowkey** [comment]
Thanks working as it should now.
